apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: postgres-platform
type: Opaque
stringData:
  POSTGRES_USER: devlabs
  POSTGRES_PASSWORD: devlabs-postgres-change-me
  POSTGRES_DB: devlabs
