apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-events
  namespace: spark
  labels:
    app.kubernetes.io/part-of: spark-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
